services:

  gitea:
    image: docker.gitea.com/gitea:1.26.1
    container_name: gitea
    env_file:
      - ./.env.app
    restart: always
    networks:
      - post_db
      - gitea
    volumes:
      - ./lab_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`gitea.docker.localhost`)"
      - "traefik.http.routers.gitea.entrypoints=websecure"
      - "traefik.http.routers.gitea.tls=true"
      # Attention: nom du réseau réel vu par Traefik est bien "gitea"
      - "traefik.docker.network=gitea"
      - "traefik.http.routers.gitea.service=gitea-service"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"

  db:
    image: docker.io/library/postgres:14
    restart: always
    env_file:
      - ./.env.db
    networks:
      - post_db
    volumes:
      - ./lab_postgres:/var/lib/postgresql/data

  traefik:
    image: traefik:v3.7.5
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true      
    networks:
      - gitea
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs:ro
      - ./dynamic:/dynamic:ro
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--providers.file.filename=/dynamic/tls.yaml"
      - "--providers.docker=true" # Providers 
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=gitea"
      - "--api.dashboard=true" # API & Dashboard for the app
      - "--api.insecure=false"
      # Observability
      - "--log.level=INFO"
      #- "--log.level=DEBUG"
      - "--accesslog=true"
      
    labels:
      - "traefik.enable=true" # Enable self‑routing
      # Dashboard router
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.docker.localhost`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
       # Basic‑auth middleware
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=${GITEA_BASIC_AUTH}" 
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth@docker"
  
networks:

  post_db:
    driver: bridge

  gitea:
    external: true

